#ASSIGNMENT=wp1p1
#ASSIGNMENT=wp1
#ASSIGNMENT=wp2
#ASSIGNMENT=wp3
ASSIGNMENT=project
TEAM_MEMBERS_CSV="Rakshith Reddy Polireddy(rpolireddy-111498989) Prashanth Soundarapandian(psoundarapan-111498721)"
# list space-separated completed components: cooperative preemptive signals swap filesystem network multicore
PROJECT_PARTS=cooperative signals,preemptive
PROJECT_POINTS=60
